apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: lighthouse-hmac-token
    mandatory: true
    properties:
    - name: token
      question: Lighthouse webhook token
      help: The webhook token is used as a secret to verify webhooks come from a trusted
        source
      generator: hmac
  - name: lighthouse-oauth-token
    mandatory: true
    properties:
    - name: token
      question: Lighthouse webhook token
      help: The webhook token is used as a secret to verify webhooks come from a trusted
        source
      generator: gitOperator.password
